_BASE_: "./Base-CRPNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETH:
    DEPTH: 50
    DILATION_ON_PER_STAGE: [False, False, False, True]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [16, 32, 64, 128, 256 ]]"]
INPUT:
  MIN_SIZE_TRAIN: (288, 320, 352, 384, 416, 448, 480)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 416
  MAX_SIZE_TEST: 800
SOLVER: # for single GPUs
  IMS_PER_BATCH: 2
  BASE_LR: 0.00125
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 1000
OUTPUT_DIR: "./output/sixdpose/coco/crpnet_Rh_50_FPN_1x"
