_BASE_: "Base-HCR-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "models/retinanet_Rh_50_FPN_128_dw_6x.pth"
  RESNETH:
    DEPTH: 50
  # ROI_HCR_HEAD:
  #   OFFSET_WEIGHTS: 1.0
  # KEYPOINT_ON: True
  # PVNET_ON: False
INPUT:
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 800
SOLVER: # for two GPUs
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (720000, 960000)
  MAX_ITER: 1080000
  CHECKPOINT_PERIOD: 120000
# DATASETS:
#   TRAIN: ("occlusion_ape_train",)
#   TEST: ("occlusion_ape_val",)
OUTPUT_DIR: "./output/sixdpose/coco/hcr_rcnn_Rh_50_FPN_3x"