_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_PVNET_HEAD:
    DECODER_ON: True
    POOLER_RESOLUTION: 28
    HEATMAP_SIZE: 112
SOLVER: # for single GPUs
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 90000
OUTPUT_DIR: "./output/sixdpose/coco/pvnet_kptrcnn_R_50_panoptic_FPN_1x"
# OUTPUT_DIR: "./output"
# OUTPUT_DIR: "./output/sixdpose/coco/pvnet_kptrcnn_hmsize112_R_50_FPN_1x"  # worse than hmsize 56