_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 9
SOLVER: # for single GPUs
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (12000, 16000)
  MAX_ITER: 18000
OUTPUT_DIR: "./output/sixdpose/keypoint_rcnn_R_50_FPN_1x_ape_fps8"
INPUT:
  MIN_SIZE_TEST: 0  # diable resize in testing
  # MIN_SIZE_TRAIN: (384, 416, 448, 480, 512, 544)  # v2
  # MIN_SIZE_TRAIN: (480, ) # v3
  MIN_SIZE_TRAIN: (416, 448, 480, 512, 544, 576)  # v4
  KEYPOINT_FORMAT: 'fps8'   # 'bb8', 'fps8', 'bb8+fps8'
TEST:
  # KEYPOINT_OKS_SIGMAS: [.1, .1, .1, .1, .1, .1, .1, .1, .1, .1,.1, .1, .1, .1, .1, .1, .1]
  KEYPOINT_OKS_SIGMAS: [.1, .1, .1, .1, .1, .1, .1, .1, .1]
DATASETS:
  TRAIN: ("occlusion_ape_train",)
  TEST: ("occlusion_ape_val",)
