_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/R-50.pkl"
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 8
  RESNETS:
    DEPTH: 50
SOLVER: # for single GPUs
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (12000, 16000)
  MAX_ITER: 18000
OUTPUT_DIR: "./output/sixdpose/mask_rcnn_R_50_FPN_1x_v4"
INPUT:
  MIN_SIZE_TEST: 0  # diable resize in testing
  # MIN_SIZE_TRAIN: (384, 416, 448, 480, 512, 544)  # v2
  # MIN_SIZE_TRAIN: (480, ) # v3
  MIN_SIZE_TRAIN: (416, 448, 480, 512, 544, 576)  # v4
