_BASE_: "Base-PVNet-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "models/faster_rcnn_Rh_50_FPN_128_6x.pth"
  RESNETH:
    DEPTH: 50
  ROI_PVNET_HEAD:
    MASK_WEIGHTS: 1.0
    VERTEX_WEIGHTS: 2.0
    DECODER_ON: False
    HEATMAP_SIZE: 56
INPUT:
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 800
SOLVER: # for two GPUs
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (240000, 320000)
  MAX_ITER: 360000
  CHECKPOINT_PERIOD: 40000
DATASETS:
  TRAIN: ("occlusion_can_train",)
  TEST: ("occlusion_can_val",)
OUTPUT_DIR: "./output/sixdpose/occlusion/can/pvnet_rcnn_Rh_50_FPN_1x"
